name: Build and Publish to AWS
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup IndexNow # Generate files dynamically to prevent them from being leaked in public repositories.
        run: echo ${{ secrets.INDEXNOW_KEY }} > static/${{ secrets.INDEXNOW_KEY }}.txt
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0
      - name: Build
        run: zola build
      - uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: public
          bucket: ${{ secrets.S3_BUCKET }}
          private: true
          delete-removed: true
          cache: 604800
          bucket-region: eu-west-1
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
